### ISSUE TITLE
label of persistent items not set to display as default "appellation in a language"

### ISSUE THREAD

**Issue by KleiolabDK** [geovistory/toolbox-streams#88]
the default label-display of "appellation in a language" forall persistent item classes has been revoked. 

In the "default project", all persistent classes had the label-setting as this:

![image](https://user-images.githubusercontent.com/51605237/235360409-003206a2-f47d-4dc3-8169-119f29eb4e5f.png)

**Comment by joschne** [comment]
@KleiolabDK 
Can you please clarify your expectation: Did you expect the label-setting of persistent classes in the "default project" to have a field #1  with "has appellation"? Or did you expect the toolbox streams to fall back to "has appellation" in case there is no label-setting for a class?

The difference between the old warehouse and toolbox streams is: The old warehouse fell back to "has appellation" in case there is no label-setting for a class. Toolbox streams does not do so. 
The label-settings were not changed during migration.

The difference between before and now leads to missing labels in case of missing label-settings. 

Proposal: By far the fastest solution is to add the label-settings to all persistent item classes. It can also be done using SQL, to ensure no class is forgotten. It should be done at a moment without high usage of Geovistory to avoid bad user experiences due to latency.

Do you agree with the proposal?

**Comment by KleiolabDK** [comment]
@joschne, yes I was referring to the fall-back -behaviour.

lets discuss your way forward quickly.

**Comment by joschne** [comment]
The label settings for all classes available at the time of writing are created in the default configuration project, as proposed above.
